"""build.py - figures, run-dependent numbers and paper.pdf from paper/latex/main.tex (pdflatex + bibtex).

    python paper/build.py                # writes paper/figures/*, paper/latex/numbers.tex and paper/paper.pdf
    python paper/build.py --pages DIR    # also rasterize every page to DIR for a layout check

The Jev paragraph, table rows and figure panel appear only once runs/explore/scaleup/jev/analysis.json
exists (see deploy/jev/README.md); nothing else needs editing.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
TEX = HERE / "latex"
JEV = ROOT / "runs/explore/scaleup/jev/analysis.json"
INTELIF = ROOT / "runs/explore/scaleup/intelif_all/analysis.json"


def _latency(seconds: float) -> str:
    return f"{seconds * 1000:.0f}\\,ms" if seconds < 1 else f"{seconds:.1f}\\,s"


def numbers() -> str:
    """LaTeX macros for every number that depends on a run that may not exist yet."""
    intelif = json.loads(INTELIF.read_text())
    lines = ["% generated by paper/build.py - do not edit", "\\newif\\ifjevresults"]
    if JEV.exists():
        jev = json.loads(JEV.read_text())
        lines += [
            "\\jevresultstrue",
            f"\\newcommand{{\\jevscore}}{{{jev['norm_score']:.2f}}}",
            f"\\newcommand{{\\jevregret}}{{{jev['regret_beam']:.2f}}}",
            f"\\newcommand{{\\jevlatency}}{{{_latency(jev['latency_p50_s'])}}}",
            f"\\newcommand{{\\jevdecisions}}{{{jev['decisions']}}}",
            f"\\newcommand{{\\efivedecisions}}{{{intelif['decisions']} + {jev['decisions']}}}",
        ]
    else:
        lines += [
            "\\jevresultsfalse",
            *(f"\\newcommand{{\\{m}}}{{}}" for m in ("jevscore", "jevregret", "jevlatency", "jevdecisions")),
            f"\\newcommand{{\\efivedecisions}}{{{intelif['decisions']}}}",
        ]
    return "\n".join(lines) + "\n"


def latex() -> Path:
    def run(*cmd: str) -> None:
        r = subprocess.run(cmd, cwd=TEX, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        if r.returncode != 0:
            sys.stdout.write(r.stdout[-4000:])
            raise SystemExit(f"{cmd[0]} failed")

    for tool in ("pdflatex", "bibtex"):
        if not shutil.which(tool):
            raise SystemExit(f"{tool} not found; install TeX Live (e.g. apt install texlive-latex-extra texlive-fonts-recommended)")
    run("pdflatex", "-interaction=nonstopmode", "-halt-on-error", "main")
    run("bibtex", "main")
    run("pdflatex", "-interaction=nonstopmode", "-halt-on-error", "main")
    run("pdflatex", "-interaction=nonstopmode", "-halt-on-error", "main")
    log = (TEX / "main.log").read_text(errors="replace")
    for needle in ("undefined references", "Citation `", "Reference `"):
        if needle in log:
            print("warning:", next(l for l in log.splitlines() if needle in l))
    pdf = HERE / "paper.pdf"
    shutil.copyfile(TEX / "main.pdf", pdf)
    return pdf


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pages", default="", help="directory for PNG renders of every page (layout check)")
    ap.add_argument("--skip_figures", action="store_true")
    args = ap.parse_args()
    if not args.skip_figures:
        subprocess.run([sys.executable, str(HERE / "figures.py")], check=True, cwd=ROOT)
    (TEX / "numbers.tex").write_text(numbers())
    pdf = latex()
    print("PDF:", pdf)
    if args.pages:
        os.makedirs(args.pages, exist_ok=True)
        subprocess.run(["pdftoppm", "-r", "80", "-png", str(pdf), os.path.join(args.pages, "page")], check=True)
        print("pages:", sorted(os.listdir(args.pages)))


if __name__ == "__main__":
    main()
